# Generated by Django 5.2.3 on 2025-06-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_size_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='code',
            field=models.CharField(default=True, max_length=10),
            preserve_default=False,
        ),
    ]
