# Generated by Django 5.2.3 on 2025-06-27 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_size_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='products',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='products',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='products',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='products',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='size',
            name='code',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.CharField(default=True, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='currentprice',
            field=models.PositiveIntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='orignalprice',
            field=models.PositiveIntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productsize',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='size',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='products.products'),
        ),
        migrations.AlterField(
            model_name='productcolorimage',
            name='image',
            field=models.ImageField(upload_to='product_color_images/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
