# Generated by Django 5.2.3 on 2025-06-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_category_name_remove_products_base_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcolor',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='productcolor',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
